#!/bin/bash

for opt
do
	case $opt in
		*=*) arg="${opt/*=/}" ;;
		*) arg="" ;;
	esac
	
	case $opt in
		--help | -help | -h | -?)
			cat << EOF
Usage: clean.sh

Removes autogenerated files.
EOF
			exit 0 ;;
		*)
			echo "Unknown option $opt." 1>&2
			exit 1
			;;
	esac
done

for i in *.in
do
	rm -fv "${i/%.in/}"
done


		
